{% set name = "pytrunc" %}
{% set version = "2.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytrunc/pytrunc-{{ version }}.tar.gz
  sha256: 5cd210c94fa5152bd6b98ef446b6171ade2391e071c2c9fdbc01fc7bc5ecd866

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - netcdf4
    - xarray

test:
  imports:
    - pytrunc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hygeos/pytrunc
  summary: Scattering phase matrix truncation Python tool for radiative transfer applications.
  license: Apache-2.0
  license_url: https://github.com/hygeos/pytrunc/blob/main/LICENSE.txt
  license_file: LICENSE.txt
  dev_url: https://github.com/hygeos/pytrunc

extra:
  recipe-maintainers:
    - musmoulana
